// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AggragateStats struct {
	Won   int `json:"won"`
	Lost  int `json:"lost"`
	Total int `json:"total"`
}

type CrewRank struct {
	Ladder []*PlayerAggragateStats `json:"ladder"`
}

type CrewmateStats struct {
	Games *AggragateStats `json:"games"`
}

type ImposterStats struct {
	Games *AggragateStats `json:"games"`
}

type OverallStats struct {
	Games *AggragateStats `json:"games"`
}

type PlayerAggragateStats struct {
	Name     string         `json:"name"`
	Overall  *OverallStats  `json:"overall"`
	Imposter *ImposterStats `json:"imposter"`
	Crewmate *CrewmateStats `json:"crewmate"`
}
